---

- name: Create the files directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files"
    state: directory

- name: Create app container
  docker_container:
    name: "{{application_name}}"
    image: "namelivia/{{application_name}}:latest"
    memory: "200MB"
    pull: true
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
        awslogs-region: "{{cloudwatch_region}}"
        awslogs-group: "{{cloudwatch_log_group}}"
        awslogs-stream: "{{application_name}}"
    networks:
      - name: "pomerium"
    exposed_ports:
      - "80"
    env:
      DATABASE_URL: "{{database_url}}"
      NOTIFICATIONS_SERVICE_ENDPOINT: "{{notifications_service_endpoint}}"
      IMAGES_SERVICE_ENDPOINT: "{{images_service_endpoint}}"
      JOURNALING_SERVICE_ENDPOINT: "{{journaling_service_endpoint}}"
      USER_INFO_SERVICE_ENDPOINT: "{{user_info_service_endpoint}}"

- include_role:
    name: namelivia.postgres
    tasks_from: create-postgres-database-if-not-exists

- include_role:
    name: namelivia.fastapi
    tasks_from: upgrade-alembic

- include_role:
    name: namelivia.backups
    tasks_from: setup-postgres-database-backups

- include_role:
    name: namelivia.backups
    tasks_from: setup-s3-backups
